( defvar h " h " )
( defvar e " e " )
( defvar l " l " )
( defvar o " o " )
( defvar tab " " )
( defvar w " w " )
( defvar r " r " )
( defvar d " d " )

( format f h )
( format f e )
( format f l )
( format f l )
( format f o )
( format f tab )
( format f w )
( format f o )
( format f r )
( format f l )
( format f d )