( defvar W " W " )
( defvar h " h " )
( defvar a " a " )
( defvar t " t " )
( defvar i " i " )
( defvar s " s " )
( defvar tab " " )
( defvar y " y " )
( defvar o " o " )
( defvar u " u " )
( defvar r " r " )
( defvar n " n " )
( defvar m " m " )
( defvar e " e " )
( defvar quest " ? " )
( defvar tran " \n " )

( defvar H " H " )
( defvar l " l " )
( defvar comma " , " )
( defvar exclam " ! " )


( format f W )
( format f h )
( format f a )
( format f t )
( format f tab )
( format f i )
( format f s )
( format f tab )
( format f y )
( format f o )
( format f u )
( format f r )
( format f tab )
( format f n )
( format f a )
( format f m )
( format f e )
( format f quest )
( format f tran )


( format f H )
( format f e )
( format f l )
( format f l )
( format f o )
( format f comma )
( format f tab )

( defvar name )
( loop
    ( setq name ( read ) )
    ( format f name )
)

( format f exclam )