(
    ( defvar h " h " )
    ( defvar e " e " )
    ( defvar l " l " )
    ( defvar o " o " )
    ( defvar tab " " )
    ( defvar w " w " )
    ( defvar r " r " )
    ( defvar d " d " )
    
    ( print h )
    ( print e )
    ( print l )
    ( print l )
    ( print o )
    ( print tab )
    ( print w )
    ( print o )
    ( print r )
    ( print l )
    ( print d )
)